### ISSUE TITLE
Evaluator / Object Implementation

### ISSUE THREAD

**Issue by dineshUmasankar** [dineshUmasankar/YARTBML#33]
We'll follow along with book in order to evaluate the AST generated from the Parser to actually interpret our programming language.

Below are the list of chapters as we continue to implement alongside sub-chapters. Please convert each sub-chapter and checkbox into an issue and create PRs to keep track of them.

There are reading material only chapter(s) only here as well. READ THEM. You will have to talk about them in the presentation briefly.

- [x] Giving Meaning to Symbols
- [x] Strategies of Evaluation
- [x] Tree-Walking Interpreter
- [x] Representing Objects
  - [x] Foundation of our Object System
  - [x] Integers
  - [x] Boolean
  - [x] Null
- [x] Evaluating Expressions
  - [x] Integer Literals
  - [x] Completing the REPL
  - [x] Boolean Literals
  - [x] Null
  - [x] Prefix Expressions
  - [x] Infix Expressions
- [x] Conditionals
- [x] Return Statements
- [x] Error Handling
- [x] Bindings & The Environment
- [x] Functions & Function Calls
- [x] Garbage Collection Discussion

**Comment by BabyKangaroo117** [comment]
Should have this finished by 4/10

**Comment by dineshUmasankar** [comment]
@BabyKangaroo117 
Went through and tested your branch, but noticed the evaluator crashes when a defined function is being called without all of its parameters being fulfilled.

Bug Replication:
```
>> let add = fn(x, y) { return x + y };
>> add(1)
```

Error Report:
```
panic: runtime error: index out of range [1] with length 1

goroutine 1 [running]:
YARTBML/evaluator.extendFunctionEnv(...)
        /home/dindesk/git/YARTBML/internal/evaluator/evaluator.go:333
YARTBML/evaluator.applyFunction({0x4d7118?, 0xc0000983c0?}, {0xc000188440, 0x1, 0xc000080008?})
        /home/dindesk/git/YARTBML/internal/evaluator/evaluator.go:319 +0x28b
YARTBML/evaluator.Eval({0x4d7398?, 0xc00018e0a0}, 0xc00009c030)
        /home/dindesk/git/YARTBML/internal/evaluator/evaluator.go:97 +0x49d
YARTBML/evaluator.Eval({0x4d7208?, 0xc000180360}, 0xc00009c030)
        /home/dindesk/git/YARTBML/internal/evaluator/evaluator.go:34 +0x9c6
YARTBML/evaluator.evalProgram(0x44c4be?, 0xc00009c030)
        /home/dindesk/git/YARTBML/internal/evaluator/evaluator.go:246 +0x85
YARTBML/evaluator.Eval({0x4d70c8?, 0xc00018c030}, 0xc00009c030)
        /home/dindesk/git/YARTBML/internal/evaluator/evaluator.go:31 +0x27a
YARTBML/repl.Start({0x4d6f48?, 0xc0000a2000?}, {0x4d6f68, 0xc0000a2008})
        /home/dindesk/git/YARTBML/internal/repl/repl.go:38 +0x1bb
main.main()
        /home/dindesk/git/YARTBML/internal/main.go:18 +0xc6
exit status 2
```
